import React,{useEffect,useState} from 'react'; import {BookOpen,Database,MessageSquareText,Send,Sparkles} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:5001';
const sample=`Acme Cloud's incident policy defines Severity 1 as a complete production outage or confirmed security breach. Sev-1 incidents require an incident commander, a dedicated communications lead, customer updates every 30 minutes, and a post-incident review within 72 hours. Severity 2 covers major degradation affecting a substantial subset of users. The standard recovery objective for Sev-1 is 60 minutes.`;
export default function App(){const [title,setTitle]=useState('Incident Response Policy');const [text,setText]=useState(sample);const [docs,setDocs]=useState([]);const [q,setQ]=useState('What are the requirements for a Severity 1 incident?');const [ans,setAns]=useState(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
 const load=()=>fetch(`${API}/api/documents`).then(r=>r.json()).then(setDocs).catch(()=>{});useEffect(load,[]);
 async function ingest(){setBusy(true);setMsg('');try{const r=await fetch(`${API}/api/documents`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,text})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMsg(`Indexed ${d.chunkCount} chunks`);load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function ask(){setBusy(true);try{const r=await fetch(`${API}/api/ask`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q})});setAns(await r.json())}finally{setBusy(false)}}
 return <div className="shell"><div className="topbar"><div className="brand"><span className="dot"/>KnowledgePilot</div><span className="badge">Grounded RAG Workspace</span></div><div className="hero"><div className="panel"><h1>Your internal knowledge, searchable with evidence.</h1><p className="sub">A multi-document RAG application with local embeddings, semantic retrieval, source citations and optional local LLM generation through Ollama.</p><div className="row"><span className="tag">RAG</span><span className="tag">Embeddings</span><span className="tag">React</span><span className="tag">MongoDB</span><span className="tag">Ollama-ready</span></div></div><div className="panel"><p className="section-title">Retrieval pipeline</p><div className="list"><div className="item">1. Chunk + overlap</div><div className="item">2. Transformer embeddings</div><div className="item">3. Cosine retrieval</div><div className="item">4. Grounded answer + citations</div></div></div></div>
 <div className="grid"><div className="panel"><p className="section-title"><Database size={15}/> Add knowledge</p><div className="field"><label>Document title</label><input value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label>Text / extracted document content</label><textarea value={text} onChange={e=>setText(e.target.value)} style={{minHeight:190}}/></div><button className="btn" onClick={ingest} disabled={busy}><BookOpen size={16}/>Index document</button>{msg&&<p className="success">{msg}</p>}<p className="section-title" style={{marginTop:20}}>Indexed documents</p>{docs.map(d=><div className="item" key={d._id}><b>{d.title}</b><div className="muted">{d.chunkCount} chunks</div></div>)}</div>
 <div className="panel"><p className="section-title"><MessageSquareText size={15}/> Ask with citations</p><div className="field"><label>Question</label><textarea value={q} onChange={e=>setQ(e.target.value)}/></div><button className="btn" onClick={ask} disabled={busy}><Send size={16}/>{busy?'Working…':'Ask KnowledgePilot'}</button>{ans&&<><div className="card" style={{marginTop:16}}><h3><Sparkles size={16}/> Grounded answer</h3><div>{ans.answer}</div></div><p className="section-title" style={{marginTop:16}}>Evidence</p>{ans.citations?.map((c,i)=><div className="card" key={i}><b>{c.title}</b> <span className="badge">{c.score.toFixed(3)}</span><div className="muted" style={{marginTop:8}}>{c.text}</div></div>)}</>}</div></div><div className="footer">No paid API required: retrieval runs locally; generation can use local Ollama or extractive fallback.</div></div>}
